### PR TITLE
Fix filter on localized fields

### LINKED ISSUE #228: [Bug]: Filter on localized fields - language & operator selection missing
### Expected behavior

In Pimcore 10 the filter on a localized field looked like this:
grafik
grafik

You could specify the language on that filter.

### Actual behavior

In Pimcore 11 - also in the [Demo](https://demo.pimcore.com/admin/) - localized fields are not shown correctly in dropdown and - if selected - there is no way to specify the language on a localized field for filtering.

grafik
grafik

Screenshots are from official demo.

### Steps to reproduce

In [Demo ](https://demo.pimcore.com/admin/)

1. Open Advanced Object Search / New
2. Select Class "News"
3. Add filter "condition"
4. Select "invisible" field between Path and Content

### PR DESCRIPTION
**Pull request by aryaantony92**
Resolves https://github.com/pimcore/advanced-object-search/issues/228

### CODE REVIEW

File: src/Service.php [hunk 1]
```diff
@@ -131,8 +131,10 @@ public function __construct(
      */
     public function getFieldDefinitionAdapter(ClassDefinition\Data $fieldDefinition, bool $considerInheritance)
     {
-        if ($this->filterLocator->has($fieldDefinition->fieldtype)) {
-            $adapter = $this->filterLocator->get($fieldDefinition->fieldtype);
+        $fieldType = ($fieldDefinition->fieldtype) ?: $fieldDefinition->getFieldType();
```
Comment (kingjia90) [inline src/Service.php]: shouldn't just go for 
```suggestion
        $fieldType = $fieldDefinition->getFieldType();
```
?

Comment (aryaantony92) [reply src/Service.php]: Yes, that's also fine
