### PR TITLE
Fix Unknown ID column in queue table

### LINKED ISSUE #196: [Bug] Unknown ID column in queue table
### Expected behavior

queue table processing works

### Actual behavior

when installing in Pimcore 10.6, queue table processing fails, 
because ID column in queue was renamed to 'id' ... see https://github.com/pimcore/advanced-object-search/pull/194/files#diff-fb84179bbc56f553ae692d24c5f2aa4d31d2106c5c723927c5e0055a6907e451R627

### Steps to reproduce

install with bundle with Pimcore 10.6 and try to create data object

### PR DESCRIPTION
**Pull request by dvesh3**
Resolves #196

### CODE REVIEW

File: src/Service.php [hunk 1]
```diff
@@ -561,16 +572,16 @@ public function doDeleteFromIndex(Concrete $object)
...
+     * @throws DoctrineDbalException
      */
     public function fillupUpdateQueue(Concrete $object)
     {
-        $db = \Pimcore\Db::get();
+        $db = Db::get();
         $idField = DataObjectService::getVersionDependentDatabaseColumnName('id');
         //need check, if there are sub objects because update on empty result set is too slow
-        $objects = $db->fetchFirstColumn('SELECT `'. $idField .'` FROM objects WHERE path LIKE ?', [$object->getFullPath() . '/%']);
+        $objects = $db->fetchFirstColumn('SELECT `'. $idField .'` FROM objects WHERE `path` LIKE ?', [$object->getFullPath() . '/%']);
```
Comment (mattamon) [inline src/Service.php:582]:
```suggestion
        $objects = $db->fetchFirstColumn('SELECT `id` FROM objects WHERE `path` LIKE ?', [$object->getFullPath() . '/%']);
```
$idField should be replace right?

**Review by mattamon — CHANGES_REQUESTED** [review]

File: src/Service.php (hunk 1 above)
Comment (dvesh3) [reply src/Service.php:582]: not here as we read data from `objects` table which can vary based on Pimcore version used.
